### ISSUE TITLE
external networks show up as ID rather than name in unraid

### ISSUE THREAD

**Issue by iarp** [dcflachs/compose_plugin#22]
I'm unsure who to report this to, I updated the Compose.Manager plugin this afternoon and this happens now.

    docker compose up -d --build

with a compose file containing an external network that my services are attached to, results in unraid displaying the custom network id rather than the name.

Is that a this plugin problem? unraid problem? compose problem?

Update: Reinstalled version 2023.05.24, restarted the machine and its back to network name instead of id.

**Comment by iarp** [comment]
2.19.0 - Compose now detects network name conflict.

That has me worried they screwed something as 2023.05.24 is 2.17.3 and latest is above 2.19

**Comment by dcflachs** [comment]
Interesting i had not noticed this change, but it is indeed on my system as well. The issue is not with this plugin, as for the most part i do not make any changes to unRAIDs built in docker pages. My guess is that something that changed in compose broke how unRAID's dockerman is enumerating network names. I would guess that this need to be an unRAID webui fix, and it will be difficult to push through as it does not effect built in unRAID functionality.

**Comment by Mainfrezzer** [comment]
The issue is a just a pure compose issue and its wonkyness with network IDs. Unraid changed the way the networking works with the macvlan fix and generates new networks upon docker start. the fix is relatively simple and i opened a pullrequest to fix it. #21

**Comment by iarp** [comment]
Just to clarify that is not a fix for this issue. I didn't want someone closing this issue if that PR merges.

**Comment by Mainfrezzer** [comment]
Sorry, i did missread at first, but as dcflachs said, this is either unRaid, although i cannot find a reason for it in the files within unraid itself, or, which is more likely since you figured it out, a compose upstream issue.

This does appear on the default bridge network, the external bridges or vtap, or any selfcreated network.
![network](https://github.com/dcflachs/compose_plugin/assets/35963833/2eaaab93-ce66-4e2d-9e58-717361a8865b)

lets me think its intended by now, although weird. Oddly enough, anything created by compose will be displayed with the networkname.


**Edit: seems like 2.18.1 is the last compose version which works fine.**
ive rebuild with the older version and it works. Nothing to do here.

![blub](https://github.com/dcflachs/compose_plugin/assets/35963833/764118ef-2cdf-49b1-a039-bdfb7b064b69)

**Comment by iarp** [comment]
In the linked issue compose just confirmed its network id from here on out.
